### ISSUE TITLE
nuitrack.h not found 

### ISSUE THREAD

**Issue by pillaya21** [UnaNancyOwen/NuiTrackSDKSample#1]
Hi, 

When I built the solution on windows with Cmake and tried to build on Visual studio I got nuitrack,h fille missing 
![image](https://user-images.githubusercontent.com/39642288/47019557-5e3f4500-d125-11e8-8ee9-001df3ea217c.png)

I added the gesture folder to the include directories for the project and I got a lot more errors: 
![image](https://user-images.githubusercontent.com/39642288/47019687-aa8a8500-d125-11e8-9a2f-c2b20046f9da.png)
 
So I am thinking I didn't include the correct file location, Which nuitrack.h should I include in my project for this issue. 
Thank you for your help.

**Comment by UnaNancyOwen** [comment]
[Gesture/nuitrack.h#L4](https://github.com/UnaNancyOwen/NuiTrackSDKSample/blob/master/sample/Gesture/nuitrack.h#L4) is <code>#include <nuitrack/Nuitrack.h></code>.
It is include header that contained in NuiTrack SDK. It is a necessary code.
It doesn't necessary to change if project is correctly generated using CMake.
Why did you change this line?

**Comment by pillaya21** [comment]
I was able to fix the issue.

**Comment by kevin0932** [comment]
Hi @pillaya21 , I met the same issue when I tried to build the samples. Would you please tell me how you fixed the issue? Thanks a lot!
