### ISSUE TITLE
Thanks :)

### ISSUE THREAD

**Issue by HassanAlmusawi** [UnaNancyOwen/NuiTrackSDKSample#5]

**Comment by UnaNancyOwen** [comment]
Please post your question to NuiTrack team, because that sample is not my sample.
BTW, Are you installed NuiTrack SDK? I think those paths are NuiTrack Runtime path.
My FindNuiTrack.cmake requres NuiTrack SDK, and NuiTrack_DIR is path to NuiTrack SDK path.

**Comment by HassanAlmusawi** [comment]
My mistake I installed it incorrectly, I installed the run time not the sdk. Thanks you.
